---
galaxy_info:
  author: Aur√©lien Maury
  description: Nginx mainline installation
  company: Aldebaran
  license: Copyrights @aldebaran.com
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie

dependencies: []
